[project]
name = "phm-101"
version = "0.1.0"
description = "Repository to learn solve phm tasks."
readme = "README.md"
authors = [
    { name = "imran-git-000", email = "chouybat@umd.edu" }
]
requires-python = ">=3.14"
dependencies = [
    "dotenv>=0.9.9",
    "ipykernel>=7.3.0",
    "loguru>=0.7.3",
    "matplotlib>=3.11.1",
    "numpy>=2.5.2",
    "pandas>=3.0.5",
    "pyarrow>=25.0.1",
    "scikit-learn>=1.9.0",
    "torch>=2.13.0",
    "torchvision>=0.28.0",
    "tqdm>=4.70.0",
]

# optional grouped dependencies that are installed only when explicitly requested
[project.optional-dependencies]

data = [
    # "polars==1.13.1"
]


# dev dependencies are installed during development but no for package
[dependency-groups]

# dependencies needed to lint and run tests
dev = [
    "pytest",
    "pytest-cov",
    "pytest-mock",
    "pytest-asyncio",
    "pytest-xdist[psutil]",
    "ruff",
    "ty",
]


[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"

[tool.pytest.ini_options]
asyncio_default_fixture_loop_scope = "function"

[[tool.uv.index]]
name = "pytorch-cu126"
url = "https://download.pytorch.org/whl/cu126"
explicit = true

[tool.uv.sources]
torch = [{ index = "pytorch-cu126" }]
torchvision = [{ index = "pytorch-cu126" }]
